eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1

server:
  port: 8080

spring:
  application:
    name: Shopping_Service # Your service name in Eureka

# Logging configuration (optional)
logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: DEBUG # You can change this to TRACE for more detailed logs

# Setting management endpoints (optional)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always # Show full details for /actuator/health

# Timeout and retry policies (optional, adjust according to needs)
ribbon:
  eureka:
    enabled: true # Enable Ribbon integration with Eureka
  ConnectTimeout: 3000
  ReadTimeout: 5000